Traccar app
azukaar/cosmos-servapps-official pull request #119
Opened 2023-12-28 09:35 UTC by TasyDevilsky

- add traccar app
- app for monitor gps devices like your car
- source: https://www.traccar.org/

2023-12-29 09:11 UTC, TasyDevilsky commented
- added Jupyter app
- app for playing with python
- source: https://jupyter.org/

2024-01-14 13:10 UTC, azukaar requested changes

2024-01-14 13:10 UTC, azukaar commented on servapps/Jupyter/cosmos-compose.json
> +        "label": "Do you want to make Jovyan sudo user ?",
This should probably just be on, it's too confusing as a question in an installer (who is Jovyan? was my first instinct lol)

2024-01-14 13:10 UTC, azukaar commented on servapps/Jupyter/cosmos-compose.json
> +        "initialValue": "8888",
You got a route for it, don't open the port

2024-01-14 13:10 UTC, azukaar commented on servapps/Jupyter/cosmos-compose.json
> +        "label": "App was sucessfully installed..."
Not required

2024-01-14 13:10 UTC, azukaar commented on servapps/Jupyter/cosmos-compose.json
> +      "GID": 1000,
UID/GID Not required I think?

2024-01-14 13:10 UTC, azukaar commented on servapps/Jupyter/cosmos-compose.json
> +          "source": "{ServiceName}-work",
If this is where the notes are going it should be a BIND to the default folder with a user input (see movies in plex or photos in photoprism

2024-01-14 13:10 UTC, azukaar commented on servapps/Traccar/cosmos-compose.json
> +          "label": "Port for your Traccar user-interface",
Same

2024-01-14 13:10 UTC, azukaar commented on servapps/Traccar/cosmos-compose.json
> +          "label": "App for tracking a various of gps."
not reqruied

2024-01-14 13:10 UTC, azukaar commented on servapps/Traccar/cosmos-compose.json
> +          "{Context.openwebsitePort}:8082/tcp"
same, this is the web UI i am assuming and you got a route to it

2024-01-14 13:10 UTC, azukaar commented on servapps/Traccar/cosmos-compose.json
> +            "target": "/opt/traccar/data",
Same, if those are the actual data make it a bind with an iput

2024-01-15 13:14 UTC, TasyDevilsky commented on servapps/Jupyter/cosmos-compose.json
> +        "label": "Do you want to make Jovyan sudo user ?",
Yep,
```
      {
        "name": "jovyanROOT",
        "label": "Do you need to use sudo in your notebooks?",
        "initialValue": false,
        "type": "checkbox"
      }
```
In the view of security its better to have it disabled by default, but some users may need this ability.

2024-01-15 20:10 UTC, azukaar commented on servapps/Jupyter/cosmos-compose.json
> +          "source": "{ServiceName}-work",
> When user delete container, there won't be option to delete this volume

that's kind of the point, the way bind/volumes have been used in the market so far, is

 - config go in volumes, then they are tightly coupled to the host server and the running container, and can easily be cleaned up and so on

 - user data go in bind, with an input that aask the user for the path, so people can easily use existing folder, or network drives in there, also they dont accidentally wipe out their data when doing admin 


Also I see your point about the user not being sudo, that said I just find it confusing to ask the user "Do you want to make Jovyan sudo user", how are they even supposed to know who is Jovyan? If I understand properly this container will create its own user instead of using 1000 as UID like any container would normally do (correct me if Im wrong), which will make it hard for most people to understand why they cant access their folder outside of Jupyter?

2024-01-16 07:41 UTC, TasyDevilsky commented on servapps/Jupyter/cosmos-compose.json
> +          "source": "{ServiceName}-work",
Yeah okey, it is much more clear to me. Thanks, I will change it.
- yep, user data should be in bind mode.
- yea sadly there is used "Jovyan" user, my question was badly choosen to users. 
- To reply to your question is that there is UID and GID this config is parent. So when jovyan create file as user or as privileged to root via sudo, the file will still be with UID 1000 on host system, so there isn't security issue on the host system.
- 
Btw, Yesterday I was dealing with free space, and it showed that use everywhere volume is not ideally :D ... `/var/lib/docker` is not inflatable....

2024-09-18 15:13 UTC, closed without merging