Update cosmos-compose.json
azukaar/cosmos-servapps-official pull request #120
Opened 2023-12-30 03:32 UTC by natevns08

update cosmos-compose for immich 1.91.0 update [full change log here](https://github.com/immich-app/immich/releases)
 - Remove typesense
 - Change postgres image

2024-01-03 14:14 UTC, azukaar commented
Please test it before you make a PR

2024-01-04 11:28 UTC, Kawanaao requested changes
You need to remove some commas and then everything will work

2024-01-04 11:28 UTC, Kawanaao commented on servapps/Immich/cosmos-compose.json
> +        "{ServiceName}-database",
Need to remove trailing coma

2024-01-04 11:28 UTC, Kawanaao commented on servapps/Immich/cosmos-compose.json
> +        "{ServiceName}-database",
Need to remove trailing coma

2024-01-14 13:29 UTC, merged