Add Gaseous-server and Baikal to marketplace
azukaar/cosmos-servapps-official pull request #163
Opened 2024-09-09 01:19 UTC by bgro82

I've tested both of these thoroughly and both worked well for me!

2024-09-09 09:13 UTC, azukaar requested changes

2024-09-09 09:13 UTC, azukaar commented on servapps/Baikal/cosmos-compose.json
> +        "label": "Do you want to make this service admin only?",
You ask for admin only but do not apply the option when selected

2024-09-09 09:13 UTC, azukaar commented on servapps/Baikal/cosmos-compose.json
> +          "source": "{ServiceName}-data",
To follow the same pattern, while config is a volume, data should be a bind to allow people to chose where to store them (see other containers for how it's setup)

2024-09-09 09:13 UTC, azukaar commented on servapps/Gaseous/cosmos-compose.json
> +      "driver": "bridge"
Any reason you force this to be on the bridge network?

2024-09-09 09:13 UTC, azukaar commented on servapps/Gaseous/cosmos-compose.json
> +        "MARIADB_PASSWORD=gaseous"
Please use the password generator (see the Nextcloud servapp for an example) You will also need to add those 3 env to the list of env to keep in update (see Nextcloud too, in the labels)

2024-09-09 17:42 UTC, bgro82 commented on servapps/Baikal/cosmos-compose.json
> +        "label": "Do you want to make this service admin only?",
Fixed!

2024-09-09 17:42 UTC, bgro82 commented on servapps/Baikal/cosmos-compose.json
> +          "source": "{ServiceName}-data",
Noted and updated

2024-09-09 17:43 UTC, bgro82 commented on servapps/Gaseous/cosmos-compose.json
> +      "driver": "bridge"
No, I think that was the default when I set it up but have removed it

2024-09-09 17:43 UTC, bgro82 commented on servapps/Gaseous/cosmos-compose.json
> +        "MARIADB_PASSWORD=gaseous"
Fixed!

2024-09-22 01:13 UTC, bgro82 reviewed
Updates requested have been completed

2024-11-03 16:41 UTC, bgro82 reviewed
All requested changes updated and tested

2026-08-27 09:39 UTC, madejackson commented
This adds Baikal, fulfilling the app request in #5.

2026-09-22 09:32 UTC, madejackson commented
**Security review: add Cosmos auth; keep enforcing `dbpass` and upload limits**

**1. Cosmos auth as first priority** — the app has its own accounts, but gate with proxy auth anyway (and wire OIDC if supported):
```jsonc
"routes": [{
  "name": "{ServiceName}",
  "target": "http://{ServiceName}:80",
  "mode": "SERVAPP",
  "AuthEnabled": true,
  "publicOpenIDName": "__route_{ServiceName}"
}]
```

**2. Hardcoded DB default.** Upstream `build/Dockerfile` ships `ARG dbpass=gaseous` / `ENV dbpass=${dbpass}` — fine here because the servapp passes `{Passwords.0}`, but please open an upstream issue so the image **fails closed** when the env var is absent.

**3. Upload limits.** Ask upstream to lower `MaxRequestBodySize`/`MultipartBodyLengthLimit` from `int.MaxValue` — a public instance is a trivial DoS today.

No image pinning required — `latest` is our preference.

---
*This review comment was drafted with the assistance of an AI assistant as part of an
automated security review of the servapp marketplace. Please independently verify the
specific claims and code references before acting on them.*

2026-09-22 10:09 UTC, madejackson requested changes
> [!IMPORTANT]
> **Merge blocked**: this PR needs the changes below before it can be merged.
> See the inline comment thread for the full context.

**Security review: add Cosmos auth; keep enforcing `dbpass` and upload limits**

**1. Cosmos auth as first priority** — the app has its own accounts, but gate with proxy auth anyway (and wire OIDC if supported):
```jsonc
"routes": [{
  "name": "{ServiceName}",
  "target": "http://{ServiceName}:80",
  "mode": "SERVAPP",
  "AuthEnabled": true
}]
```
Note: Cosmos auth uses **either** `AuthEnabled` (proxy auth) **or** `publicOpenIDName: "__route_{ServiceName}"` (public OpenID endpoint) — **never both**. Keep `AuthEnabled` unless OIDC support is added.

**2. Hardcoded DB default.** Upstream `build/Dockerfile` ships `ARG dbpass=gaseous` / `ENV dbpass=${dbpass}` — fine here because the servapp passes `{Passwords.0}`, but please open an upstream issue so the image **fails closed** when the env var is absent.

**3. Upload limits.** Ask upstream to lower `MaxRequestBodySize`/`MultipartBodyLengthLimit` from `int.MaxValue` — a public instance is a trivial DoS today.

No image pinning required — `latest` is our preference.

---
*This review was drafted with the assistance of an AI assistant as part of an automated
security review of the servapp marketplace. Please independently verify the specific claims
and code references before acting on them.*

2026-09-22 20:54 UTC, closed without merging