Piped is here.
azukaar/cosmos-servapps-official pull request #72
Opened 2023-10-31 06:31 UTC by lilkidsuave

NOTE: it is a bring your own config app, like dashy

2023-10-31 20:08 UTC, azukaar requested changes

2023-10-31 20:08 UTC, azukaar commented on servapps/Piped/cosmos-compose.json
> +       "{ServiceName}-backend": {
I'm pretty sure this is missing ENV to set the postgres credentials no?

2023-10-31 20:08 UTC, azukaar commented on servapps/Piped/cosmos-compose.json
> +              "type": "bind"
Config should be volumes (also I think mounting a single file wont work please double check if it does)

2023-10-31 20:08 UTC, azukaar commented on servapps/Piped/cosmos-compose.json
> +             "POSTGRES_PASSWORD=changeme"
PLease use the password feature to generate a random password on each install

2023-10-31 20:08 UTC, azukaar commented on servapps/Piped/cosmos-compose.json
> +    "services": {
You need to use the link feature to link the container together if you want them to talk together

https://github.com/azukaar/cosmos-servapps-official/blob/0c7788f67b1b94f39e7fefcb63d444d68b545a95/servapps/Sonarr/cosmos-compose.json#L104

2023-10-31 20:08 UTC, azukaar commented on servapps/Piped/cosmos-compose.json
> +              "type": "bind"
(Can this be a folder at all?)

2023-10-31 20:08 UTC, azukaar commented on servapps/Piped/cosmos-compose.json
> +            "cosmos-auto-update": "true"
You should keep the isolate labels too

2023-10-31 20:08 UTC, azukaar commented on servapps/Piped/cosmos-compose.json
> +          "restart": "unless-stopped",
DBs should have cosmos-persistent-env labels to keep passwords persistent even when the container is overwritten

2023-11-01 05:59 UTC, lilkidsuave commented on servapps/Piped/cosmos-compose.json
> +             "POSTGRES_PASSWORD=changeme"
What features

2023-11-01 06:00 UTC, lilkidsuave commented on servapps/Piped/cosmos-compose.json
> +              "type": "bind"
Can't be volume, requires outside config file like Dashy.
Can be folder

2023-11-01 06:00 UTC, lilkidsuave commented on servapps/Piped/cosmos-compose.json
> +       "{ServiceName}-backend": {
Fixed I think

2023-11-01 06:03 UTC, lilkidsuave commented on servapps/Piped/cosmos-compose.json
> +          "restart": "unless-stopped",
fixed

2023-11-02 14:33 UTC, jwr1 commented on servapps/Piped/cosmos-compose.json
> +             "POSTGRES_PASSWORD=changeme"
You can let cosmos generate passwords automatically, like the following: `"POSTGRES_PASSWORD={Passwords.0}"` If you increment the number (`{Passwords.1}`), I'll generate a new password, separate from the first.

2023-11-11 11:13 UTC, merged

2023-11-11 11:13 UTC, azukaar commented
Thank you!